<!DOCTYPE html>
<head>
    <title>Song 3</title>
    
<head>
<body style = "text-align:center;">
    <?php
    echo "<h1>Highschool Life</h1>";
    echo "by Repabliklan<br>";
    echo "Lyrics and Guitar Chords<br>";
    echo "     <br>";
    
    echo"[Intro]<br>";
    echo"Dm<br>";
    echo"La lala lala<br>";
    echo"C<br>";
    echo"la lala lala<br>";
    echo"Bb<br>";
    echo"la lala la la<br>";
    echo"C<br>";
    echo"la<br>";
    echo"Dm<br>";
    echo"La lala lala<br>";
    echo"C<br>";
    echo"la lala lala<br>";
    echo"Bb    C<br>";
    echo"la lala lala<br>";
    echo"Dm<br>";
    echo"la<br>";
     
    echo"[Verse 1]<br>";
    echo"Dm<br>";
    echo" High school ko<br>";
    echo"C<br>";
    echo"Ay puno ng alaala<br>";
    echo"Bb<br>";
    echo" Na hindi malilimutan<br>";
    echo"C<br>";
    echo"Lalo na ng makilala<br>";
    echo"Dm<br>";
    echo"Ang babaeng<br>";
    echo" C<br>";
    echo"Nagbigay sakin ng inspirasyon<br>";
    echo" Bb            C<br>";
    echo"Na gumawa ng homework ,At makinig sa<br>";
    echo"Dm<br>";
    echo"leksyon<br>";
    echo" Dm<br>";
    echo" Kaya nag-aral ng mabuti<br>";
    echo" C<br>";
    echo" Para sa'king future life<br>";
    echo" Bb<br>";
    echo"At lalong lalo na<br>";
    echo"C<br>";
    echo"Para sa aking future wife<br>";
    echo"Dm<br>";
    echo"At kapag break time<br>";
    echo"C<br>";
    echo"Lagi tayong magkasabay<br>";
    echo" Bb<br>";
    echo"Kinikilig ako<br>";
    echo"C                       Dm<br>";
    echo"Pag hawak ko ang iyong kamay<br>";
    echo" Dm<br>";
    echo"Habang tayo ay naglalakad<br>";
    echo" C<br>";
    echo"Pag tayo'y pauwi<br>";
    echo"Bb<br>";
    echo"Lalo akong tinatamaan<br>";
    echo"C<br>";
    echo"Pag ika'y ngumingiti<br>";
    echo"Dm<br>";
    echo"Ang lahat ng pighati<br>";
    echo"C<br>";
    echo"Ikaw ang nagtatanggal<br>";
    echo"Bb<br>";
    echo"Dahil sa iyo<br>";
    echo"C                 Dm<br>";
    echo"Kaya pasado sa periodical<br>";
    echo" Dm<br>";
    echo"Buhay ko ay nag-iba<br>";
    echo"C<br>";
    echo"Binigyan mo ng sigla<br>";
    echo"Bb<br>";
    echo"Tumaas na din ang grades ko<br>";
    echo"C<br>";
    echo"Sa matematika<br>";
    echo"Dm<br>";
    echo"kaw lang ang dahilan<br>";
    echo"C<br>";
    echo"Para to sayo mahal<br>";
    echo"Bb           C<br>";
    echo"Inaalay ko sayo, Ang natanggap kong<br>";
    echo"Dm<br>";
    echo"medal<br>";
     
    echo"[Chorus]<br>";
    echo"Dm<br>";
    echo"High school life, Oh my<br>";
    echo"C<br>";
    echo"high school life<br>";
    echo"Bb              C<br>";
    echo"Akin pang naaalala<br>";
    echo"Dm<br>";
    echo"High school days, Oh my<br>";
    echo"C<br>";
    echo"high school days<br>";
    echo"Bb         C         Dm<br>";
    echo"Na ikaw lang ang kasama<br>";
     
    echo"[Chorus]<br>";
    echo"Dm<br>";
    echo"High school life, Oh my<br>";
    echo"C<br>";
    echo"high school life<br>";
    echo"Bb              C<br>";
    echo"Akin pang naaalala<br>";
    echo"Dm<br>";
    echo"High school days, Oh my<br>";
    echo"C<br>";
    echo"high school days<br>";
    echo"Bb         C         Dm<br>";
    echo"Na ikaw lang ang kasama<br>";
     
    echo"[Verse 2]<br>";
    echo"Dm<br>";
    echo"Buhay ko ay nag-iba<br>";
    echo"C<br>";
    echo"Buhay ko ay gumanda<br>";
    echo"Bb<br>";
    echo"At maraming bumilib<br>";
    echo"C<br>";
    echo"At maraming nagtaka<br>";
    echo"Dm<br>";
    echo"Ganito pala ang feeling<br>";
    echo"C<br>";
    echo"Pag ikaw ay nagmahal<br>";
    echo"Bb           C                  Dm<br>";
    echo"Araw-araw at gabi gabi akong nagdarasal<br>";
    echo"Dm<br>";
    echo"Na sana'y ikaw na nga<br>";
    echo"C<br>";
    echo"Ang inilaan sa akin<br>";
    echo"Bb<br>";
    echo"Makasama ko sa buhay<br>";
    echo"C<br>";
    echo"Upang aking mahalin<br>";
    echo"Dm<br>";
    echo"Nang ako ay iyong sagutin<br>";
    echo"C<br>";
    echo"Muntikan na kong ma-drop<br>";
    echo"Bb         C<br>";
    echo"Pero dahil sa iyo<br>";
    echo"Dm<br>";
    echo"Naabot ko pa ang ulap<br>";
    echo"Dm<br>";
    echo"Ngunit ang kapalit<br>";
    echo"C<br>";
    echo"Bakit ka biglang nagbago<br>";
    echo"Bb<br>";
    echo"Lagi kang tulala<br>";
    echo"C<br>";
    echo"At parang lagi kang kabado<br>";
    echo"Dm<br>";
    echo"Hindi ka pumapasok<br>";
    echo"C<br>";
    echo"San ka nagpupunta<br>";
    echo"Bb                    C<br>";
    echo"Bumababa na ang mga grado mo<br>";
    echo"            Dm<br>";
    echo"Ano ba ang problema?<br>";
    echo"Dm<br>";
    echo"Nang kausapin ka<br>";
    echo"C<br>";
    echo"Bigla kang napaiyak<br>";
    echo"Bb<br>";
    echo"Mabigat ang iyong dala-dala<br>";
    echo"C<br>";
    echo"Yan ang natiyak<br>";
    echo"Dm<br>";
    echo"Nang ikaw ay tinanong<br>";
    echo"C<br>";
    echo"Hindi mo ko sinagot<br>";
    echo"Bb           C<br>";
    echo"Tumakbo ka paalis<br>";
    echo"                  Dm<br>";
    echo"Na para bang ika'y takot na takot, Baket?<br>";
     
    echo"[Chorus]<br>";
    echo"Dm<br>";
    echo"High school life, Oh my<br>";
    echo"C<br>";
    echo"high school life<br>";
    echo"Bb              C<br>";
    echo"Akin pang naaalala<br>";
    echo"Dm<br>";
    echo"High school days, Oh my<br>";
    echo"C<br>";
    echo"high school days<br>";
    echo"Bb         C         Dm<br>";
    echo"Na ikaw lang ang kasama<br>";
     
    echo"[Chorus]<br>";
    echo"Dm<br>";
    echo"High school life, Oh my<br>";
    echo"C<br>";
    echo"high school life<br>";
    echo"Bb              C<br>";
    echo"Akin pang naaalala<br>";
    echo"Dm<br>";
    echo"High school days, Oh my<br>";
    echo"C<br>";
    echo"high school days<br>";
    echo"Bb         C         Dm<br>";
    echo"Na ikaw lang ang kasama<br>";
     
    echo"[Verse 3]<br>";
    echo"Dm<br>";
    echo"Tandang-tanda ko pa<br>";
    echo"C<br>";
    echo"Lunes ng umaga nun<br>";
    echo"Bb<br>";
    echo"Bakit ang daming pulis<br>";
    echo"C<br>";
    echo"Ano bang meron ngayon?<br>";
    echo"Dm<br>";
    echo"Narinig ko ang usapan<br>";
    echo"C<br>";
    echo"Na mayron daw trahedya<br>";
    echo"Bb         C<br>";
    echo"4th year student<br>";
    echo"            Dm<br>";
    echo"Ang nakita sa kubeta<br>";
    echo"Dm<br>";
    echo"At nang inilabas<br>";
    echo"C<br>";
    echo"Labis kong ikinagulat<br>";
    echo"Bb<br>";
    echo"Pagkat ikaw ang biktimang<br>";
    echo"C<br>";
    echo"Kanilang buhat-buhat<br>";
    echo"Dm<br>";
    echo"Ikaw ay nagtapat<br>";
    echo"C<br>";
    echo"Sa sulat mo sa dingding<br>";
    echo"Bb       C<br>";
    echo"Ikaw ay ginagahasa<br>";
    echo"Dm<br>";
    echo"Ng iyong amain<br>";
    echo"Dm<br>";
    echo"Ang mga pangarap ko<br>";
    echo"C<br>";
    echo"Ay para bang nawala<br>";
    echo"Bb<br>";
    echo"Gusto kong sumigaw<br>";
    echo"C<br>";
    echo"Gusto kong magwala<br>";
    echo"Dm<br>";
    echo"Hindi makapaniwala<br>";
    echo"C<br>";
    echo"Hindi to totoo<br>";
    echo"Bb          C                   Dm<br>";
    echo"Hindi na ba kita makakasama sa kolehiyo<br>";
    echo"Dm<br>";
    echo"Ba't ngayon mo lang sinabi<br>";
    echo"C<br>";
    echo"Di mo pinaalam<br>";
    echo"Bb<br>";
    echo"Puso ko'y nagdurugo<br>";
    echo"C<br>";
    echo"Puso ko'y nagdaramdam<br>";
    echo"Dm<br>";
    echo"Matatapos na ako ngayon<br>";
    echo"C<br>";
    echo"Sa kolehiyo<br>";
    echo"Bb          C<br>";
    echo"Na dala ang alaala<br>";
    echo"              Dm<br>";
    echo"Nung high school ako<br>";
     
    echo"[Chorus]<br>";
    echo"Dm<br>";
    echo"High school life, Oh my<br>";
    echo"C<br>";
    echo"high school life<br>";
    echo"Bb              C<br>";
    echo"Akin pang naaalala<br>";
    echo"Dm<br>";
    echo"High school days, Oh my<br>";
    echo"C<br>";
    echo"high school days<br>";
    echo"Bb         C         Dm<br>";
    echo"Na ikaw lang ang kasama<br>";
     
     
    echo"[End]<br>";
    echo"Dm<br>";
    echo"High school life, Oh my<br>";
    echo"C<br>";
    echo"high school life<br>";
    echo"Bb            C<br>";
    echo"Akin pang naaalala<br>";
    echo"Dm           C<br>";
    echo"Lalo nung graduation na<br>";
    echo"Bb        C       Dm<br>";
    echo"Napaluha akong talaga<br>";
    ?>
</body>
