<!DOCTYPE html>
<head>
    <title>Song 2</title>
    
<head>
<body style = "text-align:center;">
    <?php
    echo "<h1>Classmate</h1>";
    echo "by Hambog ng Sagpro Krew<br>";
    echo "Lyrics and Guitar Chords<br>";
    echo "     <br>";
    echo"[Chorus]<br>";
    echo"A                 E<br>";
    echo"Unang araw palang minahal na kita<br>";
    echo"F#m         D<br>";
    echo"Bakit ba ganito ang aking nadama<br>";
    echo"A               E<br>";
    echo"Di man kita lubusan pang kilala<br>";
    echo"F#m          D<br>";
    echo"Eh ano naman basta mahal kita<br>";
    
    echo"[Verse 1]<br>";
    echo"A<br>";
    echo"Unang araw sa school ako'y nasa eskwelahan<br>";
    echo"E<br>";
    echo"Uniporme ay cool baka may maeksenahan<br>";
    echo"F#<br>";
    echo"Syempre meron bagong chicks ngayon nagenroll<br>";
    echo"D<br>";
    echo"Kaso yung iba mukang pang shake rattle and roll (Oh)<br>";
    echo"A<br>";
    echo"Pero iisa ang agaw pansin<br>";
    echo"E<br>";
    echo"Isang babaeng kumakain magisa sa canteen<br>";
    echo"F#m<br>";
    echo"Tapos lalo pa kong natuwa at lalong sumaya<br>";
    echo"D<br>";
    echo"Nung nalaman ko ang crush ko classmate ko pala<br>";
    echo"A<br>";
    echo"Haha ngayon nga madiskartehan<br>";
    echo"E";
    echo"Wala akong pake kung magtaray o maginarte yan<br>";
    echo"F#m<br>";
    echo"Basta gusto ko lang sabihin salitang nakakasado<br>";
    echo"D<br>";
    echo"Sa exam ng puso ko alam mo ba ikay pasado<br>";
    echo"A<br>";
    echo"Pero teka lang pangalan mo di ko pa alam<br>";
    echo"E<br>";
    echo"Hoy mister wag kang maingay tumahimik ka ma'am<br>";
    echo"F#m<br>";
    echo"Anyway di ko pa rin alam pangalan mong banal<br>";
    echo"D<br>";
    echo"Pero pwede ba tawag ko nalang sayo mahal<br>";
    
    echo"[Chorus<br>";
    echo"A                  E<br>";
    echo"Unang araw palang minahal na kita<br>";
    echo"F#m         D<br>";
    echo"Bakit ba ganito ang aking nadama<br>";
    echo"A               E<br>";
    echo"Di man kita lubusan pang kilala<br>";
    echo"F#m          D<br>";
    echo"Eh ano naman basta mahal kita<br>";
    
    echo"[Verse 2]<br>";
    echo"A<br>";
    echo"2nd subject andun kame sa may lab<br>";
    echo"E<br>";
    echo"Hindi ako nakikinig titig ako kay my love<br>";
    echo"F#m<br>";
    echo"Oo love na nga kita L-O-V-E<br>";
    echo"D<br>";
    echo"Di ko dama ang pagod ko kahit na mag P. E.<br>";
    echo"A<br>";
    echo"Pag topic ay P. C. ito'y hindi easy<br>";
    echo"E<br>";
    echo"Kaya ika'y busy pero ako'y sisi-<br>";
    echo"F#m<br>";
    echo"Ngit pa rin sa oras mo kahit ikaw ay mainis<br>";
    echo"D<br>";
    echo"Kase ikaw bumubusog sa puso ko kapag recess<br>";
    echo"A<br>";
    echo"Kung eskwelahan ang puso ko ikaw ang principal<br>";
    echo"E<br>";
    echo"Dahil sinusunod lamang nito kanyang minamahal<br>";
    echo"F#m<br>";
    echo"Daig ko pa ang first honor kapag nakita kita<br>";
    echo"D<br>";
    echo"Ikaw solution sa problem sa matematika<br>";
    echo"A<br>";
    echo"Ng buhay ko kase ikaw plus ako equals for better<br>";
    echo"E<br>";
    echo"Multiply by tiwala at love equals forever<br>";
    echo"#m<br>";
    echo"At wala ng pwedeng magdivide sa ating dalawa<br>";
    echo"D<br>";
    echo"Kase sa aklat ng Sibika tayo'y nakatalaga<br>";
    
    echo"[Chorus]<br>";
    echo"A                  E<br>";
    echo"Unang araw palang minahal na kita<br>";
    echo"F#m         D<br>";
    echo"Bakit ba ganito ang aking nadama<br>";
    echo"A               E<br>";
    echo"Di man kita lubusan pang kilala<br>";
    echo"F#m          D<br>";
    echo"Eh ano naman basta mahal kita<br>";
    
    echo"[Verse 3]<br>";
    echo"A<br>";
    echo"Tumatangge ako sa tropa pagsinabeng cutting tayo<br>";
    echo"E";
    echo"Kase misyon ko saking pagpasok maging tayo<br>";
    echo"F#m<br>";
    echo"Yayayain lang nila ko sa bilyarang kalapitan<br>";
    echo"D<br>";
    echo"Bakit pa ko dun sasamakung sayong tabe kalangitan<br>";
    echo"A<br>";
    echo"Di ba tama aking katuwiran<br>";
    echo"E<br>";
    echo"Sa eskwelahan dun lang kita natatabihan<br>";
    echo"F#m<br>";
    echo"Kapag ikaw ang seatmate ko ayoko ng lumisan<br>";
    echo"D<br>";
    echo"Sana dito nalang tayo at walang uwian (Damn)<br>";
    echo"A<br>";
    echo"Baliw na ba ko hay nako lagot<br>";
    echo"E<br>";
    echo"Saking assignment, quiz at exam pangalan mo sagot<br>";
    echo"F#m<br>";
    echo"Lagi kong hinahanap ang yong essence at presence<br>";
    echo"D<br>";
    echo"Kase kinukumpleto mo ang nonsense na sentence<br>";
    echo"A<br>";
    echo"Kaya di na aabsent you're the angel God sent<br>";
    echo"E<br>";
    echo"Ayos ba ang accent syempre laging present<br>";
    echo"F#m<br>";
    echo"Di nawawala sa school laging lumalapag<br>";
    echo"D<br>";
    echo"Kase ikaw ang dahilan kung bat ako nagsisipag<br>";
    
    echo"[Chorus]<br>";
    echo"A                  E<br>";
    echo"Unang araw palang minahal na kita<br>";
    echo"F#m         D<br>";
    echo"Bakit ba ganito ang aking nadama<br>";
    echo"A               E<br>";
    echo"Di man kita lubusan pang kilala<br>";
    echo"F#m          D<br>";
    echo"Eh ano naman basta mahal kita<br>";
    
    echo"[Verse 4]<br>";
    echo"A<br>";
    echo"Ika'y iba sa lahat masasabeng ibang klase<br>";
    echo"E<br>";
    echo"At salamat sapagkat ika'y aking naging kaklase<br>";
    echo"F#m<br>";
    echo"At ikaw ngayon ang subject dito sa aking rap<br>";
    echo"D<br>";
    echo"Kung hindi ka nakilala malamang ako'y nadrop<br>";
    echo"A<br>";
    echo"Kase tamad akong binatang sawa sa eskwelahan<br>";
    echo"E<br>";
    echo"Ngunit ikaw ay estudyante don kaya may kwenta yan<br>";
    echo"F#m<br>";
    echo"Gumawa ako ng project tulang ipapabasa<br>";
    echo"D<br>";
    echo"Di ito para kay ma'am sayo ko to papasa<br>";
    echo"A<br>";
    echo"Sana pumasa ako sayo<br>";
    echo"E<br>";
    echo"Sana magreview ka rin na umaasa ko sayo<br>";
    echo"F#m<br>";
    echo"At ang mahalin kita hindi ko yon pinagaralan<br>";
    echo"D<br>";
    echo"Dahil nadama ko yon ng kusa at agad agaran<br>";
    echo"A<br>";
    echo"Classmate kong mahal sana maisip mo na<br>";
    echo"E<br>";
    echo"Matamis mong oo ang tuturing kong diploma<br>";
    echo"F#m<br>";
    echo"At bago ka mawalay sakin sa bakasyon<br>";
    echo"D<br>";
    echo"School year na kasama ka sa puso ko babakas yon<br>";
    
    echo"[Chorus]<br>";
    echo"A                  E<br>";
    echo"Unang araw palang minahal na kita<br>";
    echo"F#m         D<br>";
    echo"Bakit ba ganito ang aking nadama<br>";
    echo"A               E<br>";
    echo"Di man kita lubusan pang kilala<br>";
    echo"F#m          D<br>";
    echo"Eh ano naman basta mahal kita<br>";
    
    echo"[Bridge]<br>";
    echo"N.C<br>";
    echo"(Classmate ko na)<br>";
    echo"A             E<br>";
    echo"Nagbigay ng kaligayahan<br>";
    echo"F#m                     D<br>";
    echo"Kaya ang nais ko ikaw ay lagi lang na nanjaan<br>";
    echo"A             E           F#m<br>";
    echo"Sana kahit tayo ay magkalayo (Classmate)<br>";
    echo"D";
    echo" Maalala mo ako (Dahil)<br>";
    
    echo"[End]<br>";
    echo"A                  E<br>";
    echo"Unang araw palang minahal na kita<br>";
    echo"F#m         D<br>";
    echo"Bakit ba ganito ang aking nadama<br>";
    echo"A               E<br>";
    echo"Di man kita lubusan pang kilala<br>";
    echo"F#m          D<br>";
    echo"Eh ano naman basta mahal kita<br>";
        
    ?>
</body>
